[[pages]]
path = "app_pages/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "app_pages/simple_chat.py"
name = "Simple Chat"
icon = "ğŸ¦œ"

[[pages]]
path = "app_pages/langchain_chatbot_sjkim.py"
name = "Chat bot(ì§„ì„ )"
icon = "ğŸ¦œ"

[[pages]]
path = "app_pages/langchain_chatbot_soo-bin.py"
name = "Chat bot(ë¹ˆìˆ˜)"
icon = "ğŸ¦œ"